[project]
name = "spacegame"
version = "0.1.0"
description = "2D Space Shooter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame-ce>=2.5.3",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "S311",   # suspicious-non-cryptographic-random-usage
    "D203",   # incorrect-blank-line-before-class
    "D213",   # multi-line-summary-second-line
    "COM812", # missing-trailing-comma, see https://docs.astral.sh/ruff/rules/missing-trailing-comma/
    "TD002",  # TODO-missing-author-name
    "TD003",  # TODO-missing-issue-link
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "S101",    # Allow asserts in tests
    "D",       # Disable all doc in tests
    "PLR2004", # Allow magic values
    "SLF001",  # Allow accessing protected attributes
]

[dependency-groups]
dev = [
  "pygbag",
  "pillow",
  "numpy",
  "pytest>=8.3.4",
  "mypy>=1.15.0",
]
lint = [
  "ruff"
]

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.black]
line-length = 120